# Unicorn Companies Dataset Exploration

This notebook explores the Unicorn Companies dataset prior to building an ETL pipeline.

Goals:

- Understand dataset structure
- Identify missing values
- Identify duplicates
- Inspect data types
- Assess data quality issues
- Define cleaning and transformation steps

### Imports

In [2]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

### Load Dataset

In [3]:
from pathlib import Path

DATA_PATH = Path("../data/raw/unicorn_companies.csv")

df = pd.read_csv(DATA_PATH)

print(f"Rows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")

Rows: 1074
Columns: 10

### First Look

In [4]:
df.head()

,Company,Valuation,Date Joined,Industry,City,Country,Continent,Year Founded,Funding,Select Investors
0,Bytedance,$180B,4/7/2017,Artificial intelligence,Beijing,China,Asia,2012,$8B,"Sequoia Capital China, SIG Asia Investments, S..."
1,SpaceX,$100B,12/1/2012,Other,Hawthorne,United States,North America,2002,$7B,"Founders Fund, Draper Fisher Jurvetson, Rothen..."
2,SHEIN,$100B,7/3/2018,E-commerce & direct-to-consumer,Shenzhen,China,Asia,2008,$2B,"Tiger Global Management, Sequoia Capital China..."
3,Stripe,$95B,1/23/2014,Fintech,San Francisco,United States,North America,2010,$2B,"Khosla Ventures, LowercaseCapital, capitalG"
4,Klarna,$46B,12/12/2011,Fintech,Stockholm,Sweden,Europe,2005,$4B,"Institutional Venture Partners, Sequoia Capita..."

### Dataset Information

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1074 entries, 0 to 1073
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Company           1074 non-null   object
 1   Valuation         1074 non-null   object
 2   Date Joined       1074 non-null   object
 3   Industry          1074 non-null   object
 4   City              1058 non-null   object
 5   Country           1074 non-null   object
 6   Continent         1074 non-null   object
 7   Year Founded      1074 non-null   int64
 8   Funding           1074 non-null   object
 9   Select Investors  1073 non-null   object
dtypes: int64(1), object(9)
memory usage: 84.0+ KB

### Column Names

In [6]:
df.columns.tolist()

['Company',
 'Valuation',
 'Date Joined',
 'Industry',
 'City',
 'Country',
 'Continent',
 'Year Founded',
 'Funding',
 'Select Investors']

### Missing Values

In [7]:
missing = pd.DataFrame({
    "missing_count": df.isna().sum(),
    "missing_percent": (
        df.isna().mean() * 100
    ).round(2)
})

missing.sort_values(
    "missing_count",
    ascending=False
)

                  missing_count  missing_percent
City                         16             1.49
Select Investors              1             0.09
Valuation                     0             0.00
Company                       0             0.00
Industry                      0             0.00
Date Joined                   0             0.00
Country                       0             0.00
Continent                     0             0.00
Year Founded                  0             0.00
Funding                       0             0.00

### Visualize Missing Values

In [8]:
missing[missing["missing_count"] > 0]

                  missing_count  missing_percent
City                         16             1.49
Select Investors              1             0.09

### Duplicate Check

In [9]:
duplicates = df.duplicated().sum()

print(
    f"Duplicate rows: {duplicates}"
)

Duplicate rows: 0

### Data Types

In [11]:
df.dtypes

Company             object
Valuation           object
Date Joined         object
Industry            object
City                object
Country             object
Continent           object
Year Founded         int64
Funding             object
Select Investors    object
dtype: object

### Summary Statistics (Numeric)

In [12]:
df.describe(include="object")

,Company,Valuation,Date Joined,Industry,City,Country,Continent,Funding,Select Investors
count,1074,1074,1074,1074,1058,1074,1074,1074,1073
unique,1073,30,639,16,256,46,6,539,1058
top,Bolt,$1B,7/13/2021,Fintech,San Francisco,United States,North America,$1B,Sequoia Capital
freq,2,471,9,224,152,562,589,60,3

### Unique Values Per Column

In [13]:
pd.DataFrame({
    "unique_values": df.nunique()
}).sort_values(
    "unique_values",
    ascending=False
)

                  unique_values
Company                    1073
Select Investors           1058
Date Joined                 639
Funding                     539
City                        256
Country                      46
Year Founded                 35
Valuation                    30
Industry                     16
Continent                     6

### Data Quality Findings

# Data Quality Findings

## Missing Values

- City: 16 missing values
- Select Investors: 1 missing value

## Duplicate Rows

- No duplicates found (verify during ETL)

## Type Issues

- Date Joined should be datetime
- Valuation should be numeric
- Funding should be numeric

## Planned Transformations

1. Standardize column names
2. Fill missing city values
3. Fill missing investor values
4. Convert Date Joined to datetime
5. Convert Valuation to billions
6. Convert Funding to billions
7. Create Joined Year feature
8. Create Company Age feature
9. Export cleaned data to SQLite